set(CMAKE_SYSTEM_NAME Windows)
set(CMAKE_SYSTEM_PROCESSOR x86_64)

set(CMAKE_C_COMPILER   x86_64-w64-mingw32-gcc)
set(CMAKE_CXX_COMPILER x86_64-w64-mingw32-g++)

# Root of the extracted SDL2 MinGW package (x86_64-w64-mingw32 folder).
if(NOT SDL2_MINGW)
    set(SDL2_MINGW "$ENV{SDL2_MINGW}")
endif()
if(NOT SDL2_MINGW)
    message(FATAL_ERROR "Set SDL2_MINGW to the SDL2 MinGW prefix, e.g. export SDL2_MINGW=~/SDL2-2.30.10/x86_64-w64-mingw32")
endif()

set(CMAKE_FIND_ROOT_PATH "${SDL2_MINGW}")
set(CMAKE_FIND_ROOT_PATH_MODE_PROGRAM NEVER)
set(CMAKE_FIND_ROOT_PATH_MODE_LIBRARY ONLY)
set(CMAKE_FIND_ROOT_PATH_MODE_INCLUDE ONLY)
set(CMAKE_FIND_ROOT_PATH_MODE_PACKAGE ONLY)